// Définitions des sous-univers
const subUniverseDefinitions = {
    "Agroalimentaire industriel": "Transformation et production à grande échelle des produits agricoles.",
    "Production biologique & circuits courts": "Cultures et élevages respectueux de l'environnement, vente locale.",
    "Agronomie & recherche appliquée": "Études scientifiques pour améliorer les rendements et la durabilité.",
    "Cultures céréalières & grandes exploitations": "Gestion de grandes surfaces agricoles mécanisées.",
    "Viticulture & œnologie": "Culture de la vigne et production du vin.",
    "Maraîchage & production maraîchère": "Culture de légumes et fruits de saison.",
    "Horticulture & pépinière": "Production de plantes ornementales et d'arbustes.",
    "Paysagisme & aménagement végétal": "Création et entretien d'espaces verts.",
    "Forêt & sylviculture durable": "Gestion et exploitation raisonnée des forêts.",
    "Élevage bovin / ovin / porcin / avicole": "Production animale pour la viande, le lait ou les œufs.",
    "Aquaculture & pêche durable": "Élevage de poissons et gestion responsable des ressources marines.",
    "Apiculture & insectes utiles": "Élevage d'abeilles et valorisation des insectes pollinisateurs.",
    "Gestion de l eau, irrigation & bassins versants": "Maîtrise des ressources hydriques pour l'agriculture.",
    "Valorisation & transformation des produits agricoles": "Fabrication de produits finis à partir des matières premières.",
    
    "Arts visuels & peinture": "Création artistique sur support visuel.",
    "Sculpture & installations": "Conception d'œuvres tridimensionnelles.",
    "Design graphique & communication visuelle": "Création d'images et supports de communication.",
    "Design produit & industriel": "Conception d'objets et produits manufacturés.",
    "Architecture intérieure & décoration": "Aménagement esthétique et fonctionnel des espaces.",
    "Photographie & image numérique": "Prise de vue, retouche et diffusion d'images.",
    "Cinéma, audiovisuel & animation": "Production de films et contenus visuels.",
    "Mode, stylisme & textile": "Conception de vêtements et accessoires.",
    "Artisanat d art traditionnel": "Création manuelle de pièces uniques.",
    "Scénographie & design d espace": "Mise en scène d'expositions ou de spectacles.",
    "Illustration & bande dessinée": "Narration visuelle et création d'univers graphiques.",
    "Patrimoine, muséographie & restauration d art": "Conservation et mise en valeur d'œuvres anciennes.",
    "Spectacle vivant & arts de la scène": "Interprétation et production théâtrale ou musicale.",
    "Métiers du luxe & savoir-faire d exception": "Création haut de gamme mêlant tradition et innovation.",
    "Régie & technique du spectacle": "Gestion des aspects techniques d'événements artistiques.",
    
    "Commerce de détail & retail": "Vente directe aux consommateurs.",
    "E-commerce & marketplaces": "Vente en ligne et gestion de plateformes numériques.",
    "Vente B2B & négociation commerciale": "Relations commerciales entre entreprises.",
    "Représentation & prospection": "Développement de clientèle sur le terrain.",
    "Merchandising & mise en valeur produits": "Optimisation de la présentation des produits.",
    "Marketing stratégique": "Étude de marché et positionnement des offres.",
    "Marketing digital & réseaux sociaux": "Promotion via les outils numériques.",
    "Communication commerciale & influence": "Stratégies de persuasion et fidélisation.",
    "Achats & approvisionnement": "Sélection et négociation avec les fournisseurs.",
    "Gestion de rayon & management de point de vente": "Pilotage opérationnel des équipes et stocks.",
    "Immobilier commercial": "Vente et location d'espaces professionnels.",
    "Banque & assurance commerciale": "Vente de produits financiers et d'assurance.",
    "Service client & relation après-vente": "Suivi et satisfaction des clients.",
    "Commerce du luxe & clientèle premium": "Vente haut de gamme et expérience exclusive.",
    "Vente en ligne & marketplaces spécialisées": "Plateformes ciblées sur des niches de produits.",
    
    "Journalisme & presse écrite": "Recherche, rédaction et diffusion d'informations vérifiées.",
    "Audiovisuel & production radio/TV": "Réalisation et diffusion d'émissions ou reportages.",
    "Relations publiques & événementiel": "Gestion de l'image d'une organisation et organisation d'événements.",
    "Communication d entreprise": "Promotion interne et externe d'une marque ou institution.",
    "Communication publique & politique": "Information et influence dans le secteur public.",
    "Édition & correction": "Relecture, mise en page et diffusion d'ouvrages.",
    "Création de contenus numériques": "Production de vidéos, posts, podcasts ou blogs.",
    "Publicité & stratégie de marque": "Création de campagnes pour valoriser des produits ou services.",
    "Influence, réseaux & storytelling": "Construction d'une image de marque par la narration et les médias sociaux.",
    "Traduction & interprétation": "Passage fidèle d'un message d'une langue à une autre.",
    "Médiation culturelle & animation de projets": "Transmission de la culture au grand public.",
    "Podcasting & création audio": "Production de formats audio indépendants.",
    
    "Architecture & conception": "Création de bâtiments et espaces de vie.",
    "Gros œuvre & maçonnerie": "Construction des structures principales.",
    "Second œuvre & finitions": "Travaux de finition intérieure et extérieure.",
    "Menuiserie & charpente bois": "Fabrication et pose d'éléments en bois.",
    "Plomberie, chauffage & climatisation": "Installation et entretien des réseaux techniques.",
    "Électricité & domotique": "Réseaux électriques et automatismes du bâtiment.",
    "Travaux publics & voirie": "Infrastructures routières, ponts, réseaux.",
    "Génie civil & infrastructures": "Conception et réalisation d'ouvrages complexes.",
    "Rénovation énergétique & éco-bâtiment": "Travaux visant la performance énergétique.",
    "Études techniques & dessin bâtiment": "Plans, modélisation et conception technique.",
    "Coordination & conduite de chantier": "Organisation et suivi des travaux.",
    "Gestion immobilière & copropriétés": "Suivi administratif et technique des biens.",
    "Aménagement urbain & espaces publics": "Planification et mise en valeur des villes.",
    
    "Droit privé & judiciaire": "Défense des droits des particuliers.",
    "Droit des affaires & fiscalité": "Conseil juridique aux entreprises.",
    "Droit social & du travail": "Relations employeurs-salariés et protection sociale.",
    "Droit public & institutions": "Encadrement des collectivités et politiques publiques.",
    "Administration publique": "Gestion courante des services de l'État.",
    "Ressources humaines & médiation": "Recrutement, dialogue social et accompagnement.",
    "Gouvernance territoriale & collectivités locales": "Gestion des politiques locales.",
    "Diplomatie & relations internationales": "Représentation et négociation entre États.",
    "Gestion des marchés publics": "Commandes et appels d'offres publics.",
    "Intelligence juridique & conformité": "Veille réglementaire et prévention des risques.",
    "Notariat & professions réglementées": "Sécurisation des actes et transactions.",
    
    "Enseignement primaire": "Transmission des savoirs fondamentaux.",
    "Enseignement secondaire": "Encadrement des adolescents et préparation aux examens.",
    "Enseignement supérieur": "Formation et recherche à l'université ou en école.",
    "Formation professionnelle & continue": "Apprentissage pour adultes et salariés.",
    "Orientation & accompagnement": "Aide à la construction de parcours individuels.",
    "Coaching & développement personnel": "Accompagnement du changement et de la motivation.",
    "Ingénierie pédagogique": "Conception de programmes et supports de formation.",
    "Éducation spécialisée & médiation éducative": "Soutien aux publics fragiles.",
    "Recherche en sciences de l éducation": "Études sur les méthodes d'apprentissage.",
    "Animation socioculturelle": "Activités éducatives et sociales collectives.",
    
    "Gestion des déchets & recyclage": "Valorisation des matières usées.",
    "Traitement de l eau & dépollution": "Purification et gestion des eaux usées.",
    "Énergies renouvelables (solaire, éolien, hydraulique)": "Production d'énergie verte (solaire, éolien...).",
    "Hydrogène & stockage d énergie": "Développement des nouvelles filières énergétiques.",
    "Énergie nucléaire & sûreté": "Production d'électricité et sécurité des installations.",
    "Génie climatique & efficacité énergétique": "Optimisation de la consommation d'énergie.",
    "Adaptation au changement climatique": "Stratégies pour limiter les impacts climatiques.",
    "Bilan carbone & comptabilité environnementale": "Mesure et réduction des émissions.",
    "Écoconception & économie circulaire": "Conception durable des produits.",
    "Aménagement durable des territoires": "Urbanisme écoresponsable.",
    "Ingénierie environnementale": "Études techniques et solutions écologiques.",
    "Protection de la biodiversité & conservation": "Sauvegarde des écosystèmes.",
    "Restauration écologique & gestion des milieux naturels": "Réhabilitation d'espaces dégradés.",
    "Mobilité durable & transports propres": "Solutions de déplacement bas carbone.",
    "Agriculture régénératrice & sols vivants": "Pratiques agricoles restauratrices.",
    "Gestion des risques naturels & résilience": "Prévention et préparation face aux aléas.",
    
    "Comptabilité & fiscalité": "Suivi des comptes et déclarations fiscales.",
    "Audit & contrôle de gestion": "Vérification de la performance financière.",
    "Trésorerie & financement": "Gestion des flux et besoins de liquidités.",
    "Banque & assurance": "Services financiers aux particuliers et entreprises.",
    "Conseil en gestion de patrimoine": "Optimisation de l'épargne et des placements.",
    "Gestion d entreprise & administration": "Pilotage global d'une organisation.",
    "Finance durable & investissement responsable": "Financement éthique et vert.",
    "Gestion de projets financiers": "Conception et suivi d'opérations budgétaires.",
    "Fintech & services financiers numériques": "Innovation dans les paiements et crédits.",
    "Gestion budgétaire publique": "Comptabilité et contrôle des finances de l'État.",
    "Contrôle interne & conformité": "Sécurité et fiabilité des procédures financières.",
    
    "Cuisine gastronomique": "Création culinaire haut de gamme.",
    "Restauration collective": "Préparation de repas pour groupes.",
    "Service & sommellerie": "Accueil et conseil en salle.",
    "Hôtellerie & hébergement": "Gestion de séjours et services associés.",
    "Accueil & réception": "Premier contact et assistance clients.",
    "Tourisme local & culturel": "Valorisation du patrimoine et des territoires.",
    "Tourisme international": "Accueil et accompagnement de visiteurs étrangers.",
    "Événementiel & congrès": "Organisation d'événements professionnels.",
    "Management hôtelier": "Pilotage d'établissements touristiques.",
    "Œnotourisme & terroir": "Découverte du vin et de la gastronomie locale.",
    "Gestion durable du tourisme": "Tourisme responsable et respectueux des ressources.",
    
    "Transaction immobilière résidentielle": "Achat et vente de logements.",
    "Transaction immobilière d entreprise & commerces": "Négociation de biens professionnels.",
    "Promotion & développement immobilier": "Construction et valorisation de projets.",
    "Gestion locative & syndic de copropriété": "Administration de biens et copropriétés.",
    "Expertise & évaluation immobilière": "Analyse de la valeur d'un bien.",
    "Investissement & conseil patrimonial immobilier": "Stratégies d'achat et de placement.",
    "Aménagement foncier & urbanisme opérationnel": "Planification et gestion du sol.",
    "Immobilier social & logement accompagné": "Gestion de l'habitat pour publics fragiles.",
    "Facility management & gestion technique de bâtiments": "Maintenance et services aux bâtiments.",
    "Immobilier de luxe & biens d exception": "Gestion d'actifs haut de gamme.",
    
    "Production industrielle": "Fabrication en série de biens et produits finis.",
    "Maintenance & SAV": "Entretien et réparation des équipements.",
    "Mécanique & usinage": "Conception et transformation de pièces métalliques.",
    "Électrotechnique & automatisme": "Commande et automatisation des systèmes électriques.",
    "Robotique & cobotique": "Collaboration homme-machine dans la production.",
    "Chimie & matériaux": "Transformation de la matière et création de composés.",
    "Aéronautique & spatial": "Conception et maintenance d'aéronefs et satellites.",
    "Métallurgie & sidérurgie": "Transformation des métaux et alliages.",
    "Industrie pharmaceutique": "Fabrication de médicaments et vaccins.",
    "Plasturgie & composites": "Conception d'objets en polymères et matériaux innovants.",
    "Qualité, sécurité & environnement industriel": "Contrôle des normes et prévention des risques.",
    "Supply chain industrielle": "Coordination logistique de la production.",
    "Fabrication additive & impression 3D": "Production par couches successives.",
    "Industrie textile & habillement": "Confection et transformation des tissus.",
    "Micro-électronique & semi-conducteurs": "Production de circuits et composants électroniques.",
    "Industries extractives & carrières": "Exploitation des ressources naturelles.",
    "Construction & maintenance navale": "Bâtiment et entretien de navires.",
    
    "Logistique & entreposage": "Gestion des flux et stockage des marchandises.",
    "Supply chain management": "Pilotage global des chaînes d'approvisionnement.",
    "Douanes & commerce international": "Gestion des échanges transfrontaliers.",
    "Transport routier & livraison": "Acheminement terrestre de marchandises.",
    "Transport ferroviaire": "Exploitation et maintenance des réseaux de trains.",
    "Transport aérien": "Exploitation et organisation du trafic aérien.",
    "Transport maritime & fluvial": "Navigation commerciale et logistique portuaire.",
    "Mobilité urbaine & transports publics": "Déplacements collectifs en ville.",
    "Gestion de flotte & maintenance": "Suivi et entretien de véhicules.",
    "Logistique urbaine & dernier kilomètre": "Livraison locale et circuits courts.",
    "Activités portuaires & maritimes": "Gestion et exploitation des infrastructures portuaires.",
    "Mobilité autonome & véhicules intelligents": "Conception et exploitation de transports automatisés.",
    
    "Création d entreprise & start-up": "Lancement et développement d'activités innovantes.",
    "Gestion de projets": "Organisation et suivi d'objectifs collectifs.",
    "Innovation & transformation digitale": "Intégration de nouvelles technologies.",
    "Management d équipe": "Encadrement et motivation des collaborateurs.",
    "RSE & développement durable": "Intégration des enjeux sociaux et environnementaux.",
    "Stratégie d entreprise": "Planification des orientations à long terme.",
    "Pilotage de structures publiques ou privées": "Gouvernance et performance organisationnelle.",
    "Management interculturel": "Coordination d'équipes internationales.",
    "Conseil & accompagnement stratégique": "Analyse et recommandation pour les dirigeants.",
    "Gouvernance & leadership éthique": "Prise de décision responsable et inspirante.",
    
    "Développement web & mobile": "Création d'applications et de sites internet.",
    "DevOps & cloud computing": "Automatisation et hébergement de systèmes informatiques.",
    "Cybersécurité": "Protection des réseaux et données.",
    "Réseaux & systèmes": "Installation et maintenance des infrastructures informatiques.",
    "Intelligence artificielle & machine learning": "Conception d'algorithmes d'apprentissage.",
    "Data science & big data": "Analyse et valorisation de grandes bases de données.",
    "Réalité augmentée & métavers": "Expériences numériques immersives.",
    "UX/UI design": "Conception d'interfaces centrées sur l'utilisateur.",
    "Informatique industrielle & IoT": "Objets connectés et automatisation des processus.",
    "Logiciels métiers & ERP": "Outils de gestion pour entreprises.",
    "No-code & automation": "Création d'applications sans programmation.",
    "Design numérique & multimédia": "Graphisme et création d'environnements digitaux.",
    "Blockchain & web3": "Technologies décentralisées et sécurisées.",
    "Informatique durable & sobriété numérique": "Réduction de l'empreinte écologique du numérique.",
    "Gaming, jeux vidéo & développement ludique": "Conception de jeux interactifs.",
    "E-sport, streaming & création de contenu gaming": "Compétition et diffusion de jeux vidéo.",
    
    "Médecine générale": "Soins courants et prévention.",
    "Chirurgie & spécialités hospitalières": "Interventions et soins techniques.",
    "Radiologie & imagerie médicale": "Diagnostic par l'image.",
    "Biologie & analyses médicales": "Études de prélèvements biologiques.",
    "Pharmacie & biotechnologies": "Développement et distribution de traitements.",
    "Infirmier & soins paramédicaux": "Accompagnement des patients au quotidien.",
    "Rééducation & kinésithérapie": "Restauration des capacités physiques.",
    "Santé mentale & psychologie": "Prise en charge des troubles psychiques.",
    "Nutrition & diététique": "Équilibre alimentaire et santé.",
    "Santé publique & prévention": "Promotion du bien-être collectif.",
    "Accompagnement des personnes âgées": "Soins et assistance en gérontologie.",
    "Médecine du sport": "Prévention et suivi des sportifs.",
    "Médecine connectée & télésanté": "Soins à distance et outils numériques.",
    
    "Physique & astrophysique": "Étude des lois de l'univers et de la matière.",
    "Mathématiques & statistiques": "Modélisation et analyse quantitative.",
    "Chimie & matériaux": "Recherche sur les réactions et nouveaux matériaux.",
    "Biotechnologies": "Innovation à partir du vivant.",
    "Géosciences & climatologie": "Étude de la Terre et des phénomènes climatiques.",
    "Neurosciences & cognition": "Exploration du cerveau et du comportement.",
    "Sciences humaines & sociales": "Analyse des sociétés et comportements humains.",
    "Recherche en éducation": "Étude des processus d'apprentissage.",
    "Recherche appliquée & transfert technologique": "Passage de la science au produit.",
    "R&D en entreprise": "Innovation intégrée à la production.",
    "Études et consulting scientifique": "Expertise et accompagnement de projets techniques.",
    
    "Police & gendarmerie": "Maintien de l'ordre et protection des citoyens.",
    "Pompiers & secours": "Interventions d'urgence et sauvetage.",
    "Sécurité privée & surveillance": "Protection des biens et des personnes.",
    "Protection civile": "Organisation des secours en cas de catastrophe.",
    "Défense & armée": "Sécurité nationale et opérations extérieures.",
    "Renseignement & sécurité stratégique": "Collecte et analyse d'informations sensibles.",
    "Sécurité informatique & cyberdéfense": "Prévention des attaques numériques.",
    "Sécurité des infrastructures critiques": "Protection des réseaux essentiels (énergie, transport...).",
    "Gestion de crise & résilience territoriale": "Coordination des réponses aux urgences.",
    "Prévention des risques & sûreté publique": "Surveillance et évaluation des menaces.",
    "Industrie de défense & armement": "Conception d'équipements militaires.",
    
    "Aide à domicile": "Soutien aux personnes dépendantes.",
    "Travail social & insertion": "Accompagnement vers l'autonomie et l'emploi.",
    "Enfance & jeunesse": "Protection et éducation des jeunes publics.",
    "Handicap & inclusion": "Soutien à la participation sociale des personnes handicapées.",
    "Santé mentale & accompagnement": "Suivi social et psychologique.",
    "Animation & médiation sociale": "Création de lien et d'activités collectives.",
    "Protection de l enfance": "Défense des droits et sécurité des mineurs.",
    "Économie sociale & solidaire": "Entreprises à finalité sociale et collective.",
    "Bénévolat & engagement citoyen": "Actions solidaires et collectives.",
    "Gestion d établissements médico-sociaux": "Pilotage de structures d'accueil.",
    "Médiation familiale": "Résolution de conflits familiaux.",
    "Services à la personne & assistance familiale": "Soutien à domicile et accompagnement quotidien.",
    "Accompagnement funéraire & thanatologie": "Soutien aux familles et organisation des rites.",
    
    "Coaching sportif": "Entraînement personnalisé et motivation.",
    "Animation & loisirs": "Encadrement d'activités de détente.",
    "Éducation physique & enseignement du sport": "Formation sportive en milieu scolaire.",
    "Encadrement sportif & fédérations": "Organisation et arbitrage des pratiques.",
    "Gestion d équipements sportifs": "Direction d'installations ou clubs.",
    "Médiation par le sport": "Utilisation du sport à des fins sociales ou éducatives.",
    "Nutrition & bien-être": "Équilibre alimentaire et hygiène de vie.",
    "Sport santé & réathlétisation": "Activité physique adaptée à la santé.",
    "Organisation d événements sportifs": "Planification et logistique de compétitions.",
    "Tourisme sportif": "Voyages et séjours autour du sport.",
    "E-sport & compétition numérique": "Compétition professionnelle de jeux vidéo.",
    
    "Robotique humanoïde avancée": "Conception de robots capables d'interagir naturellement.",
    "Technologies immersives nouvelle génération (XR, haptique)": "Interfaces sensorielles et réalités augmentées.",
    "Biotechnologies avancées & bio-ingénierie": "Innovation à l'échelle du vivant.",
    "AgroTech & FoodTech": "Nouvelles technologies pour l'agriculture et l'alimentation.",
    "CleanTech & GreenTech": "Solutions technologiques pour réduire l'impact écologique.",
    "HealthTech & MedTech": "Dispositifs connectés et innovations médicales.",
    "SpaceTech & exploration spatiale": "Technologies dédiées à l'espace et aux satellites.",
    "Économie créative & travail numérique indépendant": "Nouvelles formes de métiers autonomes et digitaux."
};

// Données des 21 univers avec leurs descriptions et sous-univers
const universesData = [
    {
        id: 1,
        icon: '🌾',
        name: 'Agriculture, nature & animaux',
        description: 'Cultivez, élevez, protégez la nature et travaillez avec les animaux.',
        subUniverses: [
            {emoji: '🏭', name: 'Agroalimentaire industriel'},
            {emoji: '🌱', name: 'Production biologique & circuits courts'},
            {emoji: '🔬', name: 'Agronomie & recherche appliquée'},
            {emoji: '🌾', name: 'Cultures céréalières & grandes exploitations'},
            {emoji: '🍇', name: 'Viticulture & œnologie'},
            {emoji: '🥕', name: 'Maraîchage & production maraîchère'},
            {emoji: '🌺', name: 'Horticulture & pépinière'},
            {emoji: '🌳', name: 'Paysagisme & aménagement végétal'},
            {emoji: '🌲', name: 'Forêt & sylviculture durable'},
            {emoji: '🐄', name: 'Élevage bovin / ovin / porcin / avicole'},
            {emoji: '🐟', name: 'Aquaculture & pêche durable'},
            {emoji: '🐝', name: 'Apiculture & insectes utiles'},
            {emoji: '💧', name: 'Gestion de l eau, irrigation & bassins versants'},
            {emoji: '🏭', name: 'Valorisation & transformation des produits agricoles'}
        ]
    },
    {
        id: 2,
        icon: '🎨',
        name: 'Arts, design & création',
        description: 'Créez, dessinez et exprimez votre créativité artistique.',
        subUniverses: [
            {emoji: '🖼️', name: 'Arts visuels & peinture'},
            {emoji: '🗿', name: 'Sculpture & installations'},
            {emoji: '🎨', name: 'Design graphique & communication visuelle'},
            {emoji: '💡', name: 'Design produit & industriel'},
            {emoji: '🏠', name: 'Architecture intérieure & décoration'},
            {emoji: '📸', name: 'Photographie & image numérique'},
            {emoji: '🎬', name: 'Cinéma, audiovisuel & animation'},
            {emoji: '👗', name: 'Mode, stylisme & textile'},
            {emoji: '🏺', name: 'Artisanat d art traditionnel'},
            {emoji: '🎭', name: 'Scénographie & design d espace'},
            {emoji: '✏️', name: 'Illustration & bande dessinée'},
            {emoji: '🏛️', name: 'Patrimoine, muséographie & restauration d art'},
            {emoji: '🎪', name: 'Spectacle vivant & arts de la scène'},
            {emoji: '💎', name: 'Métiers du luxe & savoir-faire d exception'},
            {emoji: '🎚️', name: 'Régie & technique du spectacle'}
        ]
    },
    {
        id: 3,
        icon: '🛒',
        name: 'Commerce, marketing & vente',
        description: 'Vendez, négociez et développez des stratégies commerciales.',
        subUniverses: [
            {emoji: '🏪', name: 'Commerce de détail & retail'},
            {emoji: '📦', name: 'E-commerce & marketplaces'},
            {emoji: '🤝', name: 'Vente B2B & négociation commerciale'},
            {emoji: '👔', name: 'Représentation & prospection'},
            {emoji: '🛍️', name: 'Merchandising & mise en valeur produits'},
            {emoji: '📈', name: 'Marketing stratégique'},
            {emoji: '💻', name: 'Marketing digital & réseaux sociaux'},
            {emoji: '📣', name: 'Communication commerciale & influence'},
            {emoji: '🔍', name: 'Achats & approvisionnement'},
            {emoji: '🏬', name: 'Gestion de rayon & management de point de vente'},
            {emoji: '🏢', name: 'Immobilier commercial'},
            {emoji: '🏦', name: 'Banque & assurance commerciale'},
            {emoji: '☎️', name: 'Service client & relation après-vente'},
            {emoji: '💎', name: 'Commerce du luxe & clientèle premium'},
            {emoji: '🌐', name: 'Vente en ligne & marketplaces spécialisées'}
        ]
    },
    {
        id: 4,
        icon: '🎙️',
        name: 'Communication, médias & culture',
        description: 'Informez, divertissez, communiquez à travers les médias.',
        

                     subUniverses: [
            {emoji: '🗞️', name: 'Journalisme & presse écrite'},
            {emoji: '📺', name: 'Audiovisuel & production radio/TV'},
            {emoji: '🎤', name: 'Relations publiques & événementiel'},
            {emoji: '🏢', name: 'Communication d entreprise'},
            {emoji: '🏛️', name: 'Communication publique & politique'},
            {emoji: '📚', name: 'Édition & correction'},
            {emoji: '🎥', name: 'Création de contenus numériques'},
            {emoji: '📣', name: 'Publicité & stratégie de marque'},
            {emoji: '🌐', name: 'Influence, réseaux & storytelling'},
            {emoji: '🈹', name: 'Traduction & interprétation'},
            {emoji: '🎭', name: 'Médiation culturelle & animation de projets'},
            {emoji: '🎧', name: 'Podcasting & création audio'}
        ]
    },
    {
        id: 5,
        icon: '🏗️',
        name: 'Construction, BTP & habitat',
        description: 'Construisez, concevez et coordonnez des ouvrages durables.',
        subUniverses: [
            {emoji: '🏠', name: 'Architecture & conception'},
            {emoji: '🧱', name: 'Gros œuvre & maçonnerie'},
            {emoji: '🎨', name: 'Second œuvre & finitions'},
            {emoji: '🪚', name: 'Menuiserie & charpente bois'},
            {emoji: '🚿', name: 'Plomberie, chauffage & climatisation'},
            {emoji: '⚡', name: 'Électricité & domotique'},
            {emoji: '🚧', name: 'Travaux publics & voirie'},
            {emoji: '🏗️', name: 'Génie civil & infrastructures'},
            {emoji: '🌿', name: 'Rénovation énergétique & éco-bâtiment'},
            {emoji: '📐', name: 'Études techniques & dessin bâtiment'},
            {emoji: '👷', name: 'Coordination & conduite de chantier'},
            {emoji: '🏢', name: 'Gestion immobilière & copropriétés'},
            {emoji: '🏙️', name: 'Aménagement urbain & espaces publics'}
        ]
    },
    {
        id: 6,
        icon: '⚖️',
        name: 'Droit, administration & politique publique',
        description: 'Garantissez les droits, appliquez la loi et gérez l’intérêt général.',
        subUniverses: [
            {emoji: '📜', name: 'Droit privé & judiciaire'},
            {emoji: '💼', name: 'Droit des affaires & fiscalité'},
            {emoji: '👷', name: 'Droit social & du travail'},
            {emoji: '🏛️', name: 'Droit public & institutions'},
            {emoji: '🏢', name: 'Administration publique'},
            {emoji: '🧑‍⚖️', name: 'Ressources humaines & médiation'},
            {emoji: '🌍', name: 'Gouvernance territoriale & collectivités locales'},
            {emoji: '🤝', name: 'Diplomatie & relations internationales'},
            {emoji: '📑', name: 'Gestion des marchés publics'},
            {emoji: '🧠', name: 'Intelligence juridique & conformité'},
            {emoji: '✒️', name: 'Notariat & professions réglementées'}
        ]
    },
    {
        id: 7,
        icon: '📚',
        name: 'Éducation, formation & apprentissage',
        description: 'Transmettez le savoir, formez et accompagnez les apprenants.',
        subUniverses: [
            {emoji: '🏫', name: 'Enseignement primaire'},
            {emoji: '🎓', name: 'Enseignement secondaire'},
            {emoji: '🏛️', name: 'Enseignement supérieur'},
            {emoji: '🧑‍🏫', name: 'Formation professionnelle & continue'},
            {emoji: '🧭', name: 'Orientation & accompagnement'},
            {emoji: '💬', name: 'Coaching & développement personnel'},
            {emoji: '🧩', name: 'Ingénierie pédagogique'},
            {emoji: '👨‍👩‍🏫', name: 'Éducation spécialisée & médiation éducative'},
            {emoji: '🔬', name: 'Recherche en sciences de l éducation'},
            {emoji: '🎨', name: 'Animation socioculturelle'}
        ]
    },
    {
        id: 8,
        icon: '🌍',
        name: 'Environnement, climat & énergies',
        description: 'Protégez la planète et innovez pour une transition durable.',
        subUniverses: [
            {emoji: '♻️', name: 'Gestion des déchets & recyclage'},
            {emoji: '💧', name: 'Traitement de l eau & dépollution'},
            {emoji: '☀️', name: 'Énergies renouvelables (solaire, éolien, hydraulique)'},
            {emoji: '⚡', name: 'Hydrogène & stockage d énergie'},
            {emoji: '☢️', name: 'Énergie nucléaire & sûreté'},
            {emoji: '🌡️', name: 'Génie climatique & efficacité énergétique'},
            {emoji: '🌦️', name: 'Adaptation au changement climatique'},
            {emoji: '🌍', name: 'Bilan carbone & comptabilité environnementale'},
            {emoji: '🔄', name: 'Écoconception & économie circulaire'},
            {emoji: '🏞️', name: 'Aménagement durable des territoires'},
            {emoji: '🔬', name: 'Ingénierie environnementale'},
            {emoji: '🦋', name: 'Protection de la biodiversité & conservation'},
            {emoji: '🌱', name: 'Restauration écologique & gestion des milieux naturels'},
            {emoji: '🚲', name: 'Mobilité durable & transports propres'},
            {emoji: '🌾', name: 'Agriculture régénératrice & sols vivants'},
            {emoji: '⚠️', name: 'Gestion des risques naturels & résilience'}
        ]
    },
    {
        id: 9,
        icon: '💰',
        name: 'Gestion, finance & comptabilité',
        description: 'Analysez, contrôlez et sécurisez la performance financière.',
        subUniverses: [
            {emoji: '🧾', name: 'Comptabilité & fiscalité'},
            {emoji: '📊', name: 'Audit & contrôle de gestion'},
            {emoji: '💶', name: 'Trésorerie & financement'},
            {emoji: '🏦', name: 'Banque & assurance'},
            {emoji: '👨‍💼', name: 'Conseil en gestion de patrimoine'},
            {emoji: '📈', name: 'Gestion d entreprise & administration'},
            {emoji: '🌱', name: 'Finance durable & investissement responsable'},
            {emoji: '📋', name: 'Gestion de projets financiers'},
            {emoji: '💻', name: 'Fintech & services financiers numériques'},
            {emoji: '🏛️', name: 'Gestion budgétaire publique'},
            {emoji: '🔒', name: 'Contrôle interne & conformité'}
        ]
    },
    {
        id: 10,
        icon: '🏭',
        name: 'Industrie, fabrication & production',
        description: 'Produisez, transformez et innovez dans les processus industriels.',
        subUniverses: [
            {emoji: '🏭', name: 'Production industrielle'},
            {emoji: '🧰', name: 'Maintenance & SAV'},
            {emoji: '⚙️', name: 'Mécanique & usinage'},
            {emoji: '💡', name: 'Électrotechnique & automatisme'},
            {emoji: '🤖', name: 'Robotique & cobotique'},
            {emoji: '🧪', name: 'Chimie & matériaux'},
            {emoji: '🚀', name: 'Aéronautique & spatial'},
            {emoji: '🔩', name: 'Métallurgie & sidérurgie'},
            {emoji: '💊', name: 'Industrie pharmaceutique'},
            {emoji: '🧴', name: 'Plasturgie & composites'},
            {emoji: '🧯', name: 'Qualité, sécurité & environnement industriel'},
            {emoji: '🚛', name: 'Supply chain industrielle'},
            {emoji: '🖨️', name: 'Fabrication additive & impression 3D'},
            {emoji: '👕', name: 'Industrie textile & habillement'},
            {emoji: '💻', name: 'Micro-électronique & semi-conducteurs'},
            {emoji: '⛏️', name: 'Industries extractives & carrières'},
            {emoji: '⚓', name: 'Construction & maintenance navale'}
        ]
    },
    // Tu peux poursuivre de la même manière pour les univers 11 à 21.
];
    {
        id: 11,
        icon: '💼',
        name: 'Management, entrepreneuriat & stratégie',
        description: 'Dirigez, innovez et pilotez la performance d’une organisation.',
        subUniverses: [
            {emoji: '🚀', name: 'Création d entreprise & start-up'},
            {emoji: '📋', name: 'Gestion de projets'},
            {emoji: '💡', name: 'Innovation & transformation digitale'},
            {emoji: '👥', name: 'Management d équipe'},
            {emoji: '🌱', name: 'RSE & développement durable'},
            {emoji: '🎯', name: 'Stratégie d entreprise'},
            {emoji: '🏛️', name: 'Pilotage de structures publiques ou privées'},
            {emoji: '🌍', name: 'Management interculturel'},
            {emoji: '🧠', name: 'Conseil & accompagnement stratégique'},
            {emoji: '⚖️', name: 'Gouvernance & leadership éthique'}
        ]
    },
    {
        id: 12,
        icon: '💻',
        name: 'Numérique, informatique & data',
        description: 'Créez, codez et sécurisez les technologies du futur.',
        subUniverses: [
            {emoji: '🌐', name: 'Développement web & mobile'},
            {emoji: '☁️', name: 'DevOps & cloud computing'},
            {emoji: '🛡️', name: 'Cybersécurité'},
            {emoji: '💾', name: 'Réseaux & systèmes'},
            {emoji: '🤖', name: 'Intelligence artificielle & machine learning'},
            {emoji: '📊', name: 'Data science & big data'},
            {emoji: '🎮', name: 'Réalité augmentée & métavers'},
            {emoji: '🧠', name: 'UX/UI design'},
            {emoji: '🧩', name: 'Informatique industrielle & IoT'},
            {emoji: '🧾', name: 'Logiciels métiers & ERP'},
            {emoji: '⚙️', name: 'No-code & automation'},
            {emoji: '🎨', name: 'Design numérique & multimédia'},
            {emoji: '🔗', name: 'Blockchain & web3'},
            {emoji: '🌱', name: 'Informatique durable & sobriété numérique'},
            {emoji: '🎮', name: 'Gaming, jeux vidéo & développement ludique'},
            {emoji: '🏆', name: 'E-sport, streaming & création de contenu gaming'}
        ]
    },
    {
        id: 13,
        icon: '🏥',
        name: 'Santé, bien-être & médical',
        description: 'Soignez, accompagnez et contribuez à la santé des populations.',
        subUniverses: [
            {emoji: '⚕️', name: 'Médecine générale'},
            {emoji: '🔪', name: 'Chirurgie & spécialités hospitalières'},
            {emoji: '🩻', name: 'Radiologie & imagerie médicale'},
            {emoji: '🧬', name: 'Biologie & analyses médicales'},
            {emoji: '💊', name: 'Pharmacie & biotechnologies'},
            {emoji: '💉', name: 'Infirmier & soins paramédicaux'},
            {emoji: '🏃‍♂️', name: 'Rééducation & kinésithérapie'},
            {emoji: '🧠', name: 'Santé mentale & psychologie'},
            {emoji: '🥗', name: 'Nutrition & diététique'},
            {emoji: '🏥', name: 'Santé publique & prévention'},
            {emoji: '👵', name: 'Accompagnement des personnes âgées'},
            {emoji: '⚽', name: 'Médecine du sport'},
            {emoji: '📱', name: 'Médecine connectée & télésanté'}
        ]
    },
    {
        id: 14,
        icon: '🔬',
        name: 'Sciences, recherche & innovation',
        description: 'Explorez, expérimentez et inventez les connaissances de demain.',
        subUniverses: [
            {emoji: '🌌', name: 'Physique & astrophysique'},
            {emoji: '📈', name: 'Mathématiques & statistiques'},
            {emoji: '⚗️', name: 'Chimie & matériaux'},
            {emoji: '🧫', name: 'Biotechnologies'},
            {emoji: '🌍', name: 'Géosciences & climatologie'},
            {emoji: '🧠', name: 'Neurosciences & cognition'},
            {emoji: '👥', name: 'Sciences humaines & sociales'},
            {emoji: '🎓', name: 'Recherche en éducation'},
            {emoji: '🔧', name: 'Recherche appliquée & transfert technologique'},
            {emoji: '🏭', name: 'R&D en entreprise'},
            {emoji: '📊', name: 'Études et consulting scientifique'}
        ]
    },
    {
        id: 15,
        icon: '🛡️',
        name: 'Sécurité, défense & urgence',
        description: 'Protégez, intervenez et assurez la sécurité des citoyens.',
        subUniverses: [
            {emoji: '👮', name: 'Police & gendarmerie'},
            {emoji: '🚒', name: 'Pompiers & secours'},
            {emoji: '🕵️', name: 'Sécurité privée & surveillance'},
            {emoji: '🚨', name: 'Protection civile'},
            {emoji: '🪖', name: 'Défense & armée'},
            {emoji: '📡', name: 'Renseignement & sécurité stratégique'},
            {emoji: '💻', name: 'Sécurité informatique & cyberdéfense'},
            {emoji: '🏭', name: 'Sécurité des infrastructures critiques'},
            {emoji: '⚠️', name: 'Gestion de crise & résilience territoriale'},
            {emoji: '👁️', name: 'Prévention des risques & sûreté publique'},
            {emoji: '🔫', name: 'Industrie de défense & armement'}
        ]
    },
    {
        id: 16,
        icon: '🤝',
        name: 'Social, aide & solidarité',
        description: 'Aidez, accompagnez et soutenez les personnes et les communautés.',
        subUniverses: [
            {emoji: '🏠', name: 'Aide à domicile'},
            {emoji: '🧍‍♂️', name: 'Travail social & insertion'},
            {emoji: '👶', name: 'Enfance & jeunesse'},
            {emoji: '♿', name: 'Handicap & inclusion'},
            {emoji: '🧠', name: 'Santé mentale & accompagnement'},
            {emoji: '🎨', name: 'Animation & médiation sociale'},
            {emoji: '🧒', name: 'Protection de l enfance'},
            {emoji: '💼', name: 'Économie sociale & solidaire'},
            {emoji: '❤️', name: 'Bénévolat & engagement citoyen'},
            {emoji: '🏥', name: 'Gestion d établissements médico-sociaux'},
            {emoji: '👨‍👩‍⚖️', name: 'Médiation familiale'},
            {emoji: '👵', name: 'Services à la personne & assistance familiale'},
            {emoji: '⚰️', name: 'Accompagnement funéraire & thanatologie'}
        ]
    },
    {
        id: 17,
        icon: '🏋️‍♂️',
        name: 'Sport, loisirs & vie active',
        description: 'Bougez, motivez et encadrez les activités physiques et sportives.',
        subUniverses: [
            {emoji: '🏃‍♂️', name: 'Coaching sportif'},
            {emoji: '🎯', name: 'Animation & loisirs'},
            {emoji: '🏫', name: 'Éducation physique & enseignement du sport'},
            {emoji: '⚽', name: 'Encadrement sportif & fédérations'},
            {emoji: '🏟️', name: 'Gestion d équipements sportifs'},
            {emoji: '🫱', name: 'Médiation par le sport'},
            {emoji: '🥗', name: 'Nutrition & bien-être'},
            {emoji: '💪', name: 'Sport santé & réathlétisation'},
            {emoji: '🎪', name: 'Organisation d événements sportifs'},
            {emoji: '🌍', name: 'Tourisme sportif'},
            {emoji: '🎮', name: 'E-sport & compétition numérique'}
        ]
    },
    {
        id: 18,
        icon: '🤖',
        name: 'Technologies émergentes & futur du travail',
        description: 'Innovez, automatisez et inventez les métiers de demain.',
        subUniverses: [
            {emoji: '🤖', name: 'Robotique humanoïde avancée'},
            {emoji: '🕶️', name: 'Technologies immersives nouvelle génération (XR, haptique)'},
            {emoji: '🧬', name: 'Biotechnologies avancées & bio-ingénierie'},
            {emoji: '🌾', name: 'AgroTech & FoodTech'},
            {emoji: '🌱', name: 'CleanTech & GreenTech'},
            {emoji: '🩺', name: 'HealthTech & MedTech'},
            {emoji: '🛰️', name: 'SpaceTech & exploration spatiale'},
            {emoji: '💼', name: 'Économie créative & travail numérique indépendant'}
        ]
    },
    {
        id: 19,
        icon: '🏨',
        name: 'Tourisme, hôtellerie & loisirs',
        description: 'Accueillez, servez et créez des expériences inoubliables.',
        subUniverses: [
            {emoji: '🍽️', name: 'Cuisine gastronomique'},
            {emoji: '🥗', name: 'Restauration collective'},
            {emoji: '🍷', name: 'Service & sommellerie'},
            {emoji: '🏨', name: 'Hôtellerie & hébergement'},
            {emoji: '👋', name: 'Accueil & réception'},
            {emoji: '🏛️', name: 'Tourisme local & culturel'},
            {emoji: '🌎', name: 'Tourisme international'},
            {emoji: '🎪', name: 'Événementiel & congrès'},
            {emoji: '🧳', name: 'Management hôtelier'},
            {emoji: '🍇', name: 'Œnotourisme & terroir'},
            {emoji: '🌿', name: 'Gestion durable du tourisme'}
        ]
    },
    {
        id: 20,
        icon: '🏙️',
        name: 'Urbanisme, aménagement & territoires',
        description: 'Planifiez, concevez et développez des espaces durables.',
        subUniverses: [
            {emoji: '🏗️', name: 'Transaction immobilière résidentielle'},
            {emoji: '🏢', name: 'Transaction immobilière d entreprise & commerces'},
            {emoji: '🏘️', name: 'Promotion & développement immobilier'},
            {emoji: '📋', name: 'Gestion locative & syndic de copropriété'},
            {emoji: '📏', name: 'Expertise & évaluation immobilière'},
            {emoji: '💰', name: 'Investissement & conseil patrimonial immobilier'},
            {emoji: '🌍', name: 'Aménagement foncier & urbanisme opérationnel'},
            {emoji: '🏚️', name: 'Immobilier social & logement accompagné'},
            {emoji: '🧰', name: 'Facility management & gestion technique de bâtiments'},
            {emoji: '🏰', name: 'Immobilier de luxe & biens d exception'}
        ]
    },
    {
        id: 21,
        icon: '🏛️',
        name: 'Arts, culture & patrimoine',
        description: 'Préservez, restaurez et valorisez la mémoire artistique et historique.',
        subUniverses: [
            {emoji: '🎭', name: 'Médiation culturelle'},
            {emoji: '🏢', name: 'Gestion culturelle'},
            {emoji: '🏰', name: 'Patrimoine & conservation'},
            {emoji: '🖼️', name: 'Muséographie & scénographie'},
            {emoji: '🪶', name: 'Restauration d œuvres d art'},
            {emoji: '🎟️', name: 'Valorisation et tourisme culturel'},
            {emoji: '🎪', name: 'Événementiel culturel'},
            {emoji: '🎬', name: 'Production artistique & audiovisuelle'}
        ]
    }
];

